name: release

on:
  push:
    tags:
      - v*
  workflow_dispatch:

jobs:
  release:
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    name: Release
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: Install dependencies
        run: yarn install
      - name: Release
        if: success()
        env:
          CI: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: "npx semantic-release"
